#!/bin/bash
# Generate test fixture files for XLEX tests

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIXTURES_DIR="$SCRIPT_DIR/fixtures"
XLEX="cargo run --release --bin xlex --"

echo "Generating test fixtures in $FIXTURES_DIR"

# Create simple.xlsx with basic data
echo "Creating simple.xlsx..."
$XLEX create "$FIXTURES_DIR/simple.xlsx" --force
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" A1 "Name"
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" B1 "Value"
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" C1 "Date"
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" A2 "Item 1"
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" B2 "100"
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" C2 "2024-01-01"
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" A3 "Item 2"
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" B3 "200"
$XLEX cell set "$FIXTURES_DIR/simple.xlsx" C3 "2024-01-02"
echo "  Created simple.xlsx"

# Create multi-sheet.xlsx with multiple sheets
echo "Creating multi-sheet.xlsx..."
$XLEX create "$FIXTURES_DIR/multi-sheet.xlsx" --force
$XLEX sheet add "$FIXTURES_DIR/multi-sheet.xlsx" "Sales"
$XLEX sheet add "$FIXTURES_DIR/multi-sheet.xlsx" "Inventory"
$XLEX sheet add "$FIXTURES_DIR/multi-sheet.xlsx" "Summary"
$XLEX cell set "$FIXTURES_DIR/multi-sheet.xlsx" -s "Sales" A1 "Product"
$XLEX cell set "$FIXTURES_DIR/multi-sheet.xlsx" -s "Sales" B1 "Revenue"
$XLEX cell set "$FIXTURES_DIR/multi-sheet.xlsx" -s "Inventory" A1 "Item"
$XLEX cell set "$FIXTURES_DIR/multi-sheet.xlsx" -s "Inventory" B1 "Quantity"
$XLEX cell set "$FIXTURES_DIR/multi-sheet.xlsx" -s "Summary" A1 "Total Sales"
echo "  Created multi-sheet.xlsx"

# Create formulas.xlsx with various formulas
echo "Creating formulas.xlsx..."
$XLEX create "$FIXTURES_DIR/formulas.xlsx" --force
$XLEX cell set "$FIXTURES_DIR/formulas.xlsx" A1 "10"
$XLEX cell set "$FIXTURES_DIR/formulas.xlsx" A2 "20"
$XLEX cell set "$FIXTURES_DIR/formulas.xlsx" A3 "30"
$XLEX cell formula "$FIXTURES_DIR/formulas.xlsx" A4 "=SUM(A1:A3)"
$XLEX cell formula "$FIXTURES_DIR/formulas.xlsx" B1 "=A1*2"
$XLEX cell formula "$FIXTURES_DIR/formulas.xlsx" B2 "=A2*2"
$XLEX cell formula "$FIXTURES_DIR/formulas.xlsx" B3 "=A3*2"
$XLEX cell formula "$FIXTURES_DIR/formulas.xlsx" B4 "=AVERAGE(B1:B3)"
echo "  Created formulas.xlsx"

# Create template.xlsx with placeholders
echo "Creating template.xlsx..."
$XLEX template init "$FIXTURES_DIR/template.xlsx" --type report
echo "  Created template.xlsx"

# Create vars.json for template testing
echo "Creating vars.json..."
cat > "$FIXTURES_DIR/vars.json" << 'EOF'
{
  "title": "Monthly Report",
  "date": "2024-01-15",
  "author": "XLEX User",
  "summary": "This is a test report generated by XLEX",
  "item1_name": "Revenue",
  "item1_value": "$10,000",
  "item2_name": "Expenses",
  "item2_value": "$5,000"
}
EOF
echo "  Created vars.json"

# Create vars.yaml for template testing
echo "Creating vars.yaml..."
cat > "$FIXTURES_DIR/vars.yaml" << 'EOF'
title: Monthly Report
date: 2024-01-15
author: XLEX User
summary: This is a test report generated by XLEX
item1_name: Revenue
item1_value: $10,000
item2_name: Expenses
item2_value: $5,000
EOF
echo "  Created vars.yaml"

echo ""
echo "All fixtures generated successfully!"
echo "Run 'ls -la $FIXTURES_DIR' to see the files."
